# Generated by Django 2.0.5 on 2018-11-17 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=120, unique=True)),
                ('we_name', models.CharField(max_length=120)),
                ('head_pic', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('description', models.CharField(max_length=500, null=True)),
                ('display', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('comment_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('normal', '普通'), ('top', '置顶'), ('note', '通知')], default='normal', max_length=30)),
                ('display', models.BooleanField(default=True)),
                ('nick_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser', to_field='nick_name')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.Post'),
        ),
    ]
