# Generated by Django 2.0.5 on 2018-11-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0002_circleuser_date_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='circleuser',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='circleuser',
            name='type',
            field=models.CharField(choices=[('normal', '普通'), ('super', '超级用户'), ('admin', '管理员')], default='normal', max_length=120),
        ),
    ]
