# Generated by Django 2.0.5 on 2018-11-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0004_remove_circleuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type', models.IntegerField(choices=[('1', '圈子'), ('2', '评论')])),
                ('user_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('like_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
