# Generated by Django 2.0.5 on 2018-11-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0008_auto_20181118_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser'),
        ),
    ]
