# Generated by Django 2.0.5 on 2018-11-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0009_auto_20181118_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_user',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_user',
            field=models.ManyToManyField(to='circle.CircleUser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='nick_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='circle.CircleUser'),
        ),
    ]
