# Generated by Django 2.0.5 on 2018-11-18 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0010_auto_20181118_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_user',
        ),
        migrations.AddField(
            model_name='comments',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='circle.CircleUser'),
            preserve_default=False,
        ),
    ]
