# Generated by Django 2.0.5 on 2018-11-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0011_auto_20181118_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
