# Generated by Django 2.0.5 on 2018-11-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0013_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='post_id',
        ),
    ]
