# Generated by Django 2.0.5 on 2018-11-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0014_auto_20181118_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
    ]
