# Generated by Django 2.0.5 on 2018-11-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0015_auto_20181118_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='circle',
        ),
    ]
