# Generated by Django 2.0.5 on 2018-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0017_auto_20181118_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='circle',
        ),
        migrations.AddField(
            model_name='comments',
            name='circle',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
