# Generated by Django 2.0.5 on 2018-11-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0018_auto_20181118_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleuser',
            name='user',
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
