# Generated by Django 2.0.5 on 2018-11-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0019_circleuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='nick_name',
            field=models.CharField(max_length=120, primary_key=True, unique=True),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
