# Generated by Django 2.0.5 on 2018-11-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0021_auto_20181119_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='nick_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
