# Generated by Django 2.0.5 on 2018-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0023_auto_20181119_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleuser',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='nick_name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
