# Generated by Django 2.0.5 on 2018-11-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0024_auto_20181119_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circleuser',
            old_name='user_id',
            new_name='uid',
        ),
    ]
