# Generated by Django 2.0.5 on 2018-11-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0025_auto_20181119_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
