# Generated by Django 2.0.5 on 2018-11-19 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0027_auto_20181119_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dis_like_count',
            new_name='dislike_count',
        ),
    ]
