# Generated by Django 2.0.5 on 2018-11-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0028_auto_20181119_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circleuser',
            name='uid',
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='nick_name',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
