# Generated by Django 2.0.5 on 2018-11-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0030_circleuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike_count',
            new_name='dis_like_count',
        ),
    ]
