# Generated by Django 2.0.5 on 2018-11-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0038_auto_20181120_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='nick_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser'),
        ),
    ]
