# Generated by Django 2.0.5 on 2018-11-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0039_auto_20181120_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser'),
        ),
        migrations.AlterField(
            model_name='like',
            name='nick_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser'),
        ),
    ]
