# Generated by Django 2.0.5 on 2018-11-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0040_auto_20181120_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nick_name',
            new_name='uid',
        ),
    ]
