# Generated by Django 2.0.5 on 2018-11-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0041_auto_20181120_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comments',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.Post'),
        ),
    ]
