# Generated by Django 2.0.5 on 2018-11-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0042_auto_20181120_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='head_pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
