# Generated by Django 2.0.5 on 2018-11-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0043_auto_20181125_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='circleuser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
