# Generated by Django 2.0.5 on 2018-11-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0045_auto_20181125_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
