# Generated by Django 2.0.5 on 2018-11-25 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0048_auto_20181125_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.CircleUser'),
        ),
    ]
