# Generated by Django 2.0.5 on 2018-11-25 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0049_auto_20181125_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circle.Post'),
        ),
    ]
