# Generated by Django 2.0.5 on 2018-11-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0050_auto_20181125_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='type_id',
        ),
    ]
