# Generated by Django 2.0.5 on 2018-11-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0052_like_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
    ]
