# Generated by Django 2.0.5 on 2018-11-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0053_auto_20181125_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.IntegerField(choices=[(1, '圈子'), (2, '评论')]),
        ),
    ]
