# Generated by Django 2.0.5 on 2019-02-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0056_auto_20181127_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circleuser',
            old_name='type',
            new_name='u_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='p_type',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='nick_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='we_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
