# Generated by Django 2.0.5 on 2019-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0056_auto_20181127_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleuser',
            name='nick_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='we_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
