# Generated by Django 2.0.5 on 2019-02-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0058_auto_20190203_1142'),
        ('circle', '0057_auto_20190203_1213'),
    ]

    operations = [
    ]
