# Generated by Django 2.0.5 on 2019-02-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0059_merge_20190204_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
