# Generated by Django 2.0.5 on 2019-02-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0060_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
