# Generated by Django 2.0.5 on 2019-02-06 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circle', '0061_comments_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment_time',
            new_name='pub_time',
        ),
    ]
