# Generated by Django 2.0.5 on 2018-11-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
